import type { Language } from "./i18n";

export type DivineName = {
  n: number;
  arabic: string;
  transliteration: string;
  meanings: Record<Language, string>;
};

/**
 * The 99 Names of Allah (Asma-ul-Husna), in the widely used order.
 * Arabic wording is standard; translations are conventional renderings.
 */
export const ASMA_UL_HUSNA: DivineName[] = [
  { n: 1, arabic: "ٱلرَّحْمَٰنُ", transliteration: "Ar-Rahman", meanings: { en: "The Most Compassionate", ar: "الرحمن بجميع خلقه", ur: "بے حد رحم کرنے والا" } },
  { n: 2, arabic: "ٱلرَّحِيمُ", transliteration: "Ar-Raheem", meanings: { en: "The Most Merciful", ar: "الرحيم بالمؤمنين", ur: "بار بار رحم کرنے والا" } },
  { n: 3, arabic: "ٱلْمَلِكُ", transliteration: "Al-Malik", meanings: { en: "The King, The Sovereign", ar: "المالك المتصرف", ur: "بادشاہ" } },
  { n: 4, arabic: "ٱلْقُدُّوسُ", transliteration: "Al-Quddus", meanings: { en: "The Most Holy", ar: "المنزه عن النقائص", ur: "نہایت پاک" } },
  { n: 5, arabic: "ٱلسَّلَامُ", transliteration: "As-Salam", meanings: { en: "The Source of Peace", ar: "السالم من كل عيب", ur: "سلامتی دینے والا" } },
  { n: 6, arabic: "ٱلْمُؤْمِنُ", transliteration: "Al-Mu'min", meanings: { en: "The Giver of Security", ar: "المصدق لرسله المؤمِّن عباده", ur: "امن دینے والا" } },
  { n: 7, arabic: "ٱلْمُهَيْمِنُ", transliteration: "Al-Muhaymin", meanings: { en: "The Guardian, The Watchful", ar: "الرقيب على خلقه", ur: "نگہبان" } },
  { n: 8, arabic: "ٱلْعَزِيزُ", transliteration: "Al-Azeez", meanings: { en: "The Almighty", ar: "الغالب الذي لا يُغلب", ur: "غالب، زبردست" } },
  { n: 9, arabic: "ٱلْجَبَّارُ", transliteration: "Al-Jabbar", meanings: { en: "The Compeller", ar: "القاهر الذي يجبر الخلق", ur: "زبردستی نافذ کرنے والا" } },
  { n: 10, arabic: "ٱلْمُتَكَبِّرُ", transliteration: "Al-Mutakabbir", meanings: { en: "The Supreme in Greatness", ar: "المتعالي عن صفات الخلق", ur: "بڑائی والا" } },
  { n: 11, arabic: "ٱلْخَالِقُ", transliteration: "Al-Khaliq", meanings: { en: "The Creator", ar: "الموجد للأشياء من العدم", ur: "پیدا کرنے والا" } },
  { n: 12, arabic: "ٱلْبَارِئُ", transliteration: "Al-Bari'", meanings: { en: "The Originator", ar: "المبدع للخلق", ur: "بنانے والا" } },
  { n: 13, arabic: "ٱلْمُصَوِّرُ", transliteration: "Al-Musawwir", meanings: { en: "The Fashioner of Forms", ar: "المصور لخلقه كيف شاء", ur: "صورت بنانے والا" } },
  { n: 14, arabic: "ٱلْغَفَّارُ", transliteration: "Al-Ghaffar", meanings: { en: "The Ever-Forgiving", ar: "كثير المغفرة", ur: "بہت بخشنے والا" } },
  { n: 15, arabic: "ٱلْقَهَّارُ", transliteration: "Al-Qahhar", meanings: { en: "The All-Subduer", ar: "القاهر لكل شيء", ur: "سب پر غالب" } },
  { n: 16, arabic: "ٱلْوَهَّابُ", transliteration: "Al-Wahhab", meanings: { en: "The Bestower of Gifts", ar: "كثير العطاء بلا عوض", ur: "بہت عطا کرنے والا" } },
  { n: 17, arabic: "ٱلرَّزَّاقُ", transliteration: "Ar-Razzaq", meanings: { en: "The Provider", ar: "الرازق لجميع خلقه", ur: "رزق دینے والا" } },
  { n: 18, arabic: "ٱلْفَتَّاحُ", transliteration: "Al-Fattah", meanings: { en: "The Opener, The Judge", ar: "الفاتح لأبواب الرحمة", ur: "کشادگی دینے والا" } },
  { n: 19, arabic: "ٱلْعَلِيمُ", transliteration: "Al-'Aleem", meanings: { en: "The All-Knowing", ar: "المحيط علمه بكل شيء", ur: "سب کچھ جاننے والا" } },
  { n: 20, arabic: "ٱلْقَابِضُ", transliteration: "Al-Qabid", meanings: { en: "The Withholder", ar: "الذي يقبض الرزق بحكمته", ur: "تنگی کرنے والا" } },
  { n: 21, arabic: "ٱلْبَاسِطُ", transliteration: "Al-Basit", meanings: { en: "The Extender", ar: "الذي يبسط الرزق لمن يشاء", ur: "کشادگی دینے والا" } },
  { n: 22, arabic: "ٱلْخَافِضُ", transliteration: "Al-Khafid", meanings: { en: "The Abaser", ar: "الذي يخفض من يشاء", ur: "پست کرنے والا" } },
  { n: 23, arabic: "ٱلرَّافِعُ", transliteration: "Ar-Rafi'", meanings: { en: "The Exalter", ar: "الذي يرفع من يشاء", ur: "بلند کرنے والا" } },
  { n: 24, arabic: "ٱلْمُعِزُّ", transliteration: "Al-Mu'izz", meanings: { en: "The Giver of Honour", ar: "الذي يعز من يشاء", ur: "عزت دینے والا" } },
  { n: 25, arabic: "ٱلْمُذِلُّ", transliteration: "Al-Mudhill", meanings: { en: "The Giver of Dishonour", ar: "الذي يذل من يشاء", ur: "ذلت دینے والا" } },
  { n: 26, arabic: "ٱلسَّمِيعُ", transliteration: "As-Samee'", meanings: { en: "The All-Hearing", ar: "الذي يسمع كل شيء", ur: "سب سننے والا" } },
  { n: 27, arabic: "ٱلْبَصِيرُ", transliteration: "Al-Baseer", meanings: { en: "The All-Seeing", ar: "الذي يبصر كل شيء", ur: "سب دیکھنے والا" } },
  { n: 28, arabic: "ٱلْحَكَمُ", transliteration: "Al-Hakam", meanings: { en: "The Judge", ar: "الحاكم بين خلقه", ur: "فیصلہ کرنے والا" } },
  { n: 29, arabic: "ٱلْعَدْلُ", transliteration: "Al-'Adl", meanings: { en: "The Utterly Just", ar: "العادل في حكمه", ur: "انصاف کرنے والا" } },
  { n: 30, arabic: "ٱللَّطِيفُ", transliteration: "Al-Lateef", meanings: { en: "The Subtle, The Gentle", ar: "اللطيف بعباده", ur: "باریک بین، مہربان" } },
  { n: 31, arabic: "ٱلْخَبِيرُ", transliteration: "Al-Khabeer", meanings: { en: "The All-Aware", ar: "العالم ببواطن الأمور", ur: "پوری خبر رکھنے والا" } },
  { n: 32, arabic: "ٱلْحَلِيمُ", transliteration: "Al-Haleem", meanings: { en: "The Most Forbearing", ar: "الذي لا يعاجل بالعقوبة", ur: "بردبار" } },
  { n: 33, arabic: "ٱلْعَظِيمُ", transliteration: "Al-'Azeem", meanings: { en: "The Magnificent", ar: "العظيم في ذاته وصفاته", ur: "بہت عظمت والا" } },
  { n: 34, arabic: "ٱلْغَفُورُ", transliteration: "Al-Ghafoor", meanings: { en: "The Much-Forgiving", ar: "الساتر لذنوب عباده", ur: "بخشنے والا" } },
  { n: 35, arabic: "ٱلشَّكُورُ", transliteration: "Ash-Shakoor", meanings: { en: "The Most Appreciative", ar: "المجازي على القليل بالكثير", ur: "قدر دان" } },
  { n: 36, arabic: "ٱلْعَلِيُّ", transliteration: "Al-'Aliyy", meanings: { en: "The Most High", ar: "العالي فوق خلقه", ur: "بہت بلند" } },
  { n: 37, arabic: "ٱلْكَبِيرُ", transliteration: "Al-Kabeer", meanings: { en: "The Most Great", ar: "الكبير في شأنه", ur: "بہت بڑا" } },
  { n: 38, arabic: "ٱلْحَفِيظُ", transliteration: "Al-Hafeez", meanings: { en: "The Preserver", ar: "الحافظ لخلقه", ur: "حفاظت کرنے والا" } },
  { n: 39, arabic: "ٱلْمُقِيتُ", transliteration: "Al-Muqeet", meanings: { en: "The Sustainer", ar: "المقتدر الذي يقيت الخلق", ur: "قوت پہنچانے والا" } },
  { n: 40, arabic: "ٱلْحَسِيبُ", transliteration: "Al-Haseeb", meanings: { en: "The Reckoner", ar: "الكافي المحاسب لعباده", ur: "حساب لینے والا" } },
  { n: 41, arabic: "ٱلْجَلِيلُ", transliteration: "Al-Jaleel", meanings: { en: "The Majestic", ar: "الموصوف بالجلال", ur: "بزرگی والا" } },
  { n: 42, arabic: "ٱلْكَرِيمُ", transliteration: "Al-Kareem", meanings: { en: "The Most Generous", ar: "الكثير الخير والعطاء", ur: "بہت کرم کرنے والا" } },
  { n: 43, arabic: "ٱلرَّقِيبُ", transliteration: "Ar-Raqeeb", meanings: { en: "The Watchful", ar: "المراقب لأحوال عباده", ur: "نگرانی کرنے والا" } },
  { n: 44, arabic: "ٱلْمُجِيبُ", transliteration: "Al-Mujeeb", meanings: { en: "The Responsive", ar: "المجيب لدعاء عباده", ur: "دعا قبول کرنے والا" } },
  { n: 45, arabic: "ٱلْوَاسِعُ", transliteration: "Al-Wasi'", meanings: { en: "The All-Encompassing", ar: "الواسع فضله ورحمته", ur: "وسعت والا" } },
  { n: 46, arabic: "ٱلْحَكِيمُ", transliteration: "Al-Hakeem", meanings: { en: "The All-Wise", ar: "المحكم لخلقه", ur: "حکمت والا" } },
  { n: 47, arabic: "ٱلْوَدُودُ", transliteration: "Al-Wadood", meanings: { en: "The Most Loving", ar: "المحب لعباده الصالحين", ur: "بہت محبت کرنے والا" } },
  { n: 48, arabic: "ٱلْمَجِيدُ", transliteration: "Al-Majeed", meanings: { en: "The Glorious", ar: "الواسع الكرم والشرف", ur: "بزرگی و بڑائی والا" } },
  { n: 49, arabic: "ٱلْبَاعِثُ", transliteration: "Al-Ba'ith", meanings: { en: "The Resurrector", ar: "الذي يبعث الخلق يوم القيامة", ur: "دوبارہ اٹھانے والا" } },
  { n: 50, arabic: "ٱلشَّهِيدُ", transliteration: "Ash-Shaheed", meanings: { en: "The Witness", ar: "الشاهد على كل شيء", ur: "ہر چیز کا گواہ" } },
  { n: 51, arabic: "ٱلْحَقُّ", transliteration: "Al-Haqq", meanings: { en: "The Absolute Truth", ar: "الثابت الذي لا يزول", ur: "سچا، برحق" } },
  { n: 52, arabic: "ٱلْوَكِيلُ", transliteration: "Al-Wakeel", meanings: { en: "The Trustee, The Disposer of Affairs", ar: "الكفيل بأرزاق العباد", ur: "کارساز" } },
  { n: 53, arabic: "ٱلْقَوِيُّ", transliteration: "Al-Qawiyy", meanings: { en: "The All-Strong", ar: "كامل القوة", ur: "بہت طاقتور" } },
  { n: 54, arabic: "ٱلْمَتِينُ", transliteration: "Al-Mateen", meanings: { en: "The Firm, The Steadfast", ar: "الشديد القوة", ur: "نہایت مضبوط" } },
  { n: 55, arabic: "ٱلْوَلِيُّ", transliteration: "Al-Waliyy", meanings: { en: "The Protecting Friend", ar: "الناصر لأوليائه", ur: "دوست و مددگار" } },
  { n: 56, arabic: "ٱلْحَمِيدُ", transliteration: "Al-Hameed", meanings: { en: "The Praiseworthy", ar: "المستحق للحمد", ur: "قابلِ تعریف" } },
  { n: 57, arabic: "ٱلْمُحْصِي", transliteration: "Al-Muhsi", meanings: { en: "The Recorder of All", ar: "المحصي لكل شيء عددًا", ur: "سب کچھ شمار کرنے والا" } },
  { n: 58, arabic: "ٱلْمُبْدِئُ", transliteration: "Al-Mubdi'", meanings: { en: "The Initiator", ar: "المبدئ للخلق", ur: "پہلی بار پیدا کرنے والا" } },
  { n: 59, arabic: "ٱلْمُعِيدُ", transliteration: "Al-Mu'eed", meanings: { en: "The Restorer", ar: "المعيد للخلق بعد الفناء", ur: "دوبارہ پیدا کرنے والا" } },
  { n: 60, arabic: "ٱلْمُحْيِي", transliteration: "Al-Muhyi", meanings: { en: "The Giver of Life", ar: "الذي يحيي الموتى", ur: "زندگی دینے والا" } },
  { n: 61, arabic: "ٱلْمُمِيتُ", transliteration: "Al-Mumeet", meanings: { en: "The Bringer of Death", ar: "الذي يميت الأحياء", ur: "موت دینے والا" } },
  { n: 62, arabic: "ٱلْحَيُّ", transliteration: "Al-Hayy", meanings: { en: "The Ever-Living", ar: "الحي الذي لا يموت", ur: "ہمیشہ زندہ" } },
  { n: 63, arabic: "ٱلْقَيُّومُ", transliteration: "Al-Qayyoom", meanings: { en: "The Sustainer of All", ar: "القائم بنفسه المقيم لغيره", ur: "سب کو قائم رکھنے والا" } },
  { n: 64, arabic: "ٱلْوَاجِدُ", transliteration: "Al-Wajid", meanings: { en: "The Perceiver, The Finder", ar: "الذي لا يعوزه شيء", ur: "ہر چیز پانے والا" } },
  { n: 65, arabic: "ٱلْمَاجِدُ", transliteration: "Al-Majid", meanings: { en: "The Noble, The Illustrious", ar: "الكريم الماجد", ur: "بزرگی والا" } },
  { n: 66, arabic: "ٱلْوَاحِدُ", transliteration: "Al-Wahid", meanings: { en: "The One", ar: "المنفرد بالوحدانية", ur: "ایک، یکتا" } },
  { n: 67, arabic: "ٱلْأَحَدُ", transliteration: "Al-Ahad", meanings: { en: "The Unique", ar: "الأحد الذي لا شريك له", ur: "اکیلا، بے مثل" } },
  { n: 68, arabic: "ٱلصَّمَدُ", transliteration: "As-Samad", meanings: { en: "The Eternal Refuge", ar: "المقصود في الحوائج", ur: "بے نیاز، سب کا سہارا" } },
  { n: 69, arabic: "ٱلْقَادِرُ", transliteration: "Al-Qadir", meanings: { en: "The Capable", ar: "القادر على كل شيء", ur: "قدرت والا" } },
  { n: 70, arabic: "ٱلْمُقْتَدِرُ", transliteration: "Al-Muqtadir", meanings: { en: "The Omnipotent", ar: "التام القدرة", ur: "پوری قدرت رکھنے والا" } },
  { n: 71, arabic: "ٱلْمُقَدِّمُ", transliteration: "Al-Muqaddim", meanings: { en: "The Expediter", ar: "الذي يقدم من يشاء", ur: "آگے کرنے والا" } },
  { n: 72, arabic: "ٱلْمُؤَخِّرُ", transliteration: "Al-Mu'akhkhir", meanings: { en: "The Delayer", ar: "الذي يؤخر من يشاء", ur: "پیچھے کرنے والا" } },
  { n: 73, arabic: "ٱلْأَوَّلُ", transliteration: "Al-Awwal", meanings: { en: "The First", ar: "الذي ليس قبله شيء", ur: "سب سے پہلا" } },
  { n: 74, arabic: "ٱلْآخِرُ", transliteration: "Al-Akhir", meanings: { en: "The Last", ar: "الذي ليس بعده شيء", ur: "سب سے آخر" } },
  { n: 75, arabic: "ٱلظَّاهِرُ", transliteration: "Az-Zahir", meanings: { en: "The Manifest", ar: "الظاهر بآياته", ur: "ظاہر" } },
  { n: 76, arabic: "ٱلْبَاطِنُ", transliteration: "Al-Batin", meanings: { en: "The Hidden", ar: "الباطن عن الأبصار", ur: "پوشیدہ" } },
  { n: 77, arabic: "ٱلْوَالِي", transliteration: "Al-Wali", meanings: { en: "The Governor", ar: "المتولي لأمور خلقه", ur: "کارفرما" } },
  { n: 78, arabic: "ٱلْمُتَعَالِي", transliteration: "Al-Muta'ali", meanings: { en: "The Most Exalted", ar: "المتنزه عن صفات الخلق", ur: "بہت بلند و برتر" } },
  { n: 79, arabic: "ٱلْبَرُّ", transliteration: "Al-Barr", meanings: { en: "The Source of All Goodness", ar: "المحسن إلى عباده", ur: "بہت نیکی کرنے والا" } },
  { n: 80, arabic: "ٱلتَّوَّابُ", transliteration: "At-Tawwab", meanings: { en: "The Ever-Accepting of Repentance", ar: "الذي يقبل توبة عباده", ur: "توبہ قبول کرنے والا" } },
  { n: 81, arabic: "ٱلْمُنْتَقِمُ", transliteration: "Al-Muntaqim", meanings: { en: "The Avenger", ar: "المنتقم من العصاة", ur: "بدلہ لینے والا" } },
  { n: 82, arabic: "ٱلْعَفُوُّ", transliteration: "Al-'Afuww", meanings: { en: "The Pardoner", ar: "الذي يمحو الذنوب", ur: "معاف کرنے والا" } },
  { n: 83, arabic: "ٱلرَّءُوفُ", transliteration: "Ar-Ra'oof", meanings: { en: "The Most Kind", ar: "الرحيم بعباده", ur: "بہت شفقت کرنے والا" } },
  { n: 84, arabic: "مَالِكُ ٱلْمُلْكِ", transliteration: "Malik-ul-Mulk", meanings: { en: "Master of the Kingdom", ar: "مالك الملك كله", ur: "بادشاہی کا مالک" } },
  { n: 85, arabic: "ذُو ٱلْجَلَالِ وَٱلْإِكْرَامِ", transliteration: "Dhul-Jalali wal-Ikram", meanings: { en: "Lord of Majesty and Generosity", ar: "ذو العظمة والفضل", ur: "عظمت اور کرم والا" } },
  { n: 86, arabic: "ٱلْمُقْسِطُ", transliteration: "Al-Muqsit", meanings: { en: "The Equitable", ar: "العادل في قضائه", ur: "انصاف قائم کرنے والا" } },
  { n: 87, arabic: "ٱلْجَامِعُ", transliteration: "Al-Jami'", meanings: { en: "The Gatherer", ar: "الجامع للخلق ليوم القيامة", ur: "جمع کرنے والا" } },
  { n: 88, arabic: "ٱلْغَنِيُّ", transliteration: "Al-Ghaniyy", meanings: { en: "The Self-Sufficient", ar: "الغني عن كل شيء", ur: "بے نیاز" } },
  { n: 89, arabic: "ٱلْمُغْنِي", transliteration: "Al-Mughni", meanings: { en: "The Enricher", ar: "الذي يغني من يشاء", ur: "غنی کرنے والا" } },
  { n: 90, arabic: "ٱلْمَانِعُ", transliteration: "Al-Mani'", meanings: { en: "The Withholder", ar: "الذي يمنع بحكمته", ur: "روکنے والا" } },
  { n: 91, arabic: "ٱلضَّارُّ", transliteration: "Ad-Darr", meanings: { en: "The Creator of Harm", ar: "الذي يقدر الضر بحكمته", ur: "نقصان مقرر کرنے والا" } },
  { n: 92, arabic: "ٱلنَّافِعُ", transliteration: "An-Nafi'", meanings: { en: "The Creator of Good", ar: "الذي ينفع من يشاء", ur: "نفع دینے والا" } },
  { n: 93, arabic: "ٱلنُّورُ", transliteration: "An-Noor", meanings: { en: "The Light", ar: "نور السماوات والأرض", ur: "نور" } },
  { n: 94, arabic: "ٱلْهَادِي", transliteration: "Al-Hadi", meanings: { en: "The Guide", ar: "الهادي إلى الحق", ur: "ہدایت دینے والا" } },
  { n: 95, arabic: "ٱلْبَدِيعُ", transliteration: "Al-Badee'", meanings: { en: "The Incomparable Originator", ar: "المبدع للخلق بلا مثال", ur: "بے مثال پیدا کرنے والا" } },
  { n: 96, arabic: "ٱلْبَاقِي", transliteration: "Al-Baqi", meanings: { en: "The Everlasting", ar: "الباقي بلا انتهاء", ur: "ہمیشہ باقی رہنے والا" } },
  { n: 97, arabic: "ٱلْوَارِثُ", transliteration: "Al-Warith", meanings: { en: "The Inheritor of All", ar: "الوارث لكل شيء", ur: "سب کا وارث" } },
  { n: 98, arabic: "ٱلرَّشِيدُ", transliteration: "Ar-Rasheed", meanings: { en: "The Guide to the Right Path", ar: "المرشد إلى الرشاد", ur: "راہِ راست دکھانے والا" } },
  { n: 99, arabic: "ٱلصَّبُورُ", transliteration: "As-Saboor", meanings: { en: "The Most Patient", ar: "الذي لا يعاجل بالعقوبة", ur: "بہت صبر کرنے والا" } },
];

export function nameMeaning(name: DivineName, lang: Language): string {
  return name.meanings[lang] ?? name.meanings.en;
}
